class Case {
    constructor(name, score) {
        this.name = name;
        this.score = score;
    }
}

const cases = [
    new Case("Case1", Math.floor(Math.random() * 10) + 1),
    new Case("Case2", Math.floor(Math.random() * 10) + 1),
    new Case("Case3", Math.floor(Math.random() * 10) + 1),
    new Case("Case4", Math.floor(Math.random() * 10) + 1),
    new Case("Case5", Math.floor(Math.random() * 10) + 1),
    new Case("Case6", Math.floor(Math.random() * 10) + 1),
    new Case("Case7", Math.floor(Math.random() * 10) + 1),
    new Case("Case8", Math.floor(Math.random() * 10) + 1),
    new Case("Case9", Math.floor(Math.random() * 10) + 1),
    new Case("Case10", Math.floor(Math.random() * 10) + 1),
    new Case("Case11", Math.floor(Math.random() * 10) + 1),
    new Case("Case12", Math.floor(Math.random() * 10) + 1),
    new Case("Case13", Math.floor(Math.random() * 10) + 1),
    new Case("Case14", Math.floor(Math.random() * 10) + 1),
    new Case("Case15", Math.floor(Math.random() * 10) + 1),
    new Case("Case16", Math.floor(Math.random() * 10) + 1),
    new Case("Case17", Math.floor(Math.random() * 10) + 1),
    new Case("Case18", Math.floor(Math.random() * 10) + 1),
    new Case("Case19", Math.floor(Math.random() * 10) + 1),
    new Case("Case20", Math.floor(Math.random() * 10) + 1),
    new Case("Case21", Math.floor(Math.random() * 10) + 1),
    new Case("Case22", Math.floor(Math.random() * 10) + 1),
    new Case("Case23", Math.floor(Math.random() * 10) + 1),
    new Case("Case24", Math.floor(Math.random() * 10) + 1),
    new Case("Case25", Math.floor(Math.random() * 10) + 1),
    new Case("Case26", Math.floor(Math.random() * 10) + 1),
    new Case("Case27", Math.floor(Math.random() * 10) + 1),
    new Case("Case28", Math.floor(Math.random() * 10) + 1),
    new Case("Case29", Math.floor(Math.random() * 10) + 1),
    new Case("Case30", Math.floor(Math.random() * 10) + 1),
    new Case("Case31", Math.floor(Math.random() * 10) + 1),
    new Case("Case32", Math.floor(Math.random() * 10) + 1),
    new Case("Case33", Math.floor(Math.random() * 10) + 1),
    new Case("Case34", Math.floor(Math.random() * 10) + 1),
    new Case("Case35", Math.floor(Math.random() * 10) + 1),
    new Case("Case36", Math.floor(Math.random() * 10) + 1),
    new Case("Case37", Math.floor(Math.random() * 10) + 1),
    new Case("Case38", Math.floor(Math.random() * 10) + 1),
    new Case("Case39", Math.floor(Math.random() * 10) + 1),
    new Case("Case40", Math.floor(Math.random() * 10) + 1),
    new Case("Case41", Math.floor(Math.random() * 10) + 1),
    new Case("Case42", Math.floor(Math.random() * 10) + 1),
    new Case("Case43", Math.floor(Math.random() * 10) + 1),
    new Case("Case44", Math.floor(Math.random() * 10) + 1),
    new Case("Case45", Math.floor(Math.random() * 10) + 1),
    new Case("Case46", Math.floor(Math.random() * 10) + 1),
    new Case("Case47", Math.floor(Math.random() * 10) + 1),
    new Case("Case48", Math.floor(Math.random() * 10) + 1),
    new Case("Case49", Math.floor(Math.random() * 10) + 1),
    new Case("Case50", Math.floor(Math.random() * 10) + 1),
    new Case("Case51", Math.floor(Math.random() * 10) + 1),
    new Case("Case52", Math.floor(Math.random() * 10) + 1),
    new Case("Case53", Math.floor(Math.random() * 10) + 1),
    new Case("Case54", Math.floor(Math.random() * 10) + 1),
    new Case("Case55", Math.floor(Math.random() * 10) + 1),
    new Case("Case56", Math.floor(Math.random() * 10) + 1),
    new Case("Case57", Math.floor(Math.random() * 10) + 1),
    new Case("Case58", Math.floor(Math.random() * 10) + 1),
    new Case("Case59", Math.floor(Math.random() * 10) + 1),
    new Case("Case60", Math.floor(Math.random() * 10) + 1),
    new Case("Case61", Math.floor(Math.random() * 10) + 1),
    new Case("Case62", Math.floor(Math.random() * 10) + 1),
    new Case("Case63", Math.floor(Math.random() * 10) + 1),
    new Case("Case64", Math.floor(Math.random() * 10) + 1),
    new Case("Case65", Math.floor(Math.random() * 10) + 1),
    new Case("Case66", Math.floor(Math.random() * 10) + 1),
    new Case("Case67", Math.floor(Math.random() * 10) + 1),
    new Case("Case68", Math.floor(Math.random() * 10) + 1),
    new Case("Case69", Math.floor(Math.random() * 10) + 1),
    new Case("Case70", Math.floor(Math.random() * 10) + 1),
    new Case("Case71", Math.floor(Math.random() * 10) + 1),
    new Case("Case72", Math.floor(Math.random() * 10) + 1),
    new Case("Case73", Math.floor(Math.random() * 10) + 1),
    new Case("Case74", Math.floor(Math.random() * 10) + 1),
    new Case("Case75", Math.floor(Math.random() * 10) + 1),
    new Case("Case76", Math.floor(Math.random() * 10) + 1),
    new Case("Case77", Math.floor(Math.random() * 10) + 1),
    new Case("Case78", Math.floor(Math.random() * 10) + 1),
    new Case("Case79", Math.floor(Math.random() * 10) + 1),
    new Case("Case80", Math.floor(Math.random() * 10) + 1),
    new Case("Case81", Math.floor(Math.random() * 10) + 1),
    new Case("Case82", Math.floor(Math.random() * 10) + 1),
    new Case("Case83", Math.floor(Math.random() * 10) + 1),
    new Case("Case84", Math.floor(Math.random() * 10) + 1),
    new Case("Case85", Math.floor(Math.random() * 10) + 1),
    new Case("Case86", Math.floor(Math.random() * 10) + 1),
    new Case("Case87", Math.floor(Math.random() * 10) + 1),
    new Case("Case88", Math.floor(Math.random() * 10) + 1),
    new Case("Case89", Math.floor(Math.random() * 10) + 1),
    new Case("Case90", Math.floor(Math.random() * 10) + 1),
    new Case("Case91", Math.floor(Math.random() * 10) + 1),
    new Case("Case92", Math.floor(Math.random() * 10) + 1),
    new Case("Case93", Math.floor(Math.random() * 10) + 1),
    new Case("Case94", Math.floor(Math.random() * 10) + 1),
    new Case("Case95", Math.floor(Math.random() * 10) + 1),
    new Case("Case96", Math.floor(Math.random() * 10) + 1),
    new Case("Case97", Math.floor(Math.random() * 10) + 1),
    new Case("Case98", Math.floor(Math.random() * 10) + 1),
    new Case("Case99", Math.floor(Math.random() * 10) + 1),
    new Case("Case100", Math.floor(Math.random() * 10) + 1),
];

module.exports = cases;
